# Generated by Django 5.0.1 on 2024-01-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
