# Generated by Django 5.0.1 on 2024-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='juree',
            field=models.BooleanField(default=True),
        ),
    ]
