# Generated by Django 5.0.1 on 2024-01-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_juree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='juree',
        ),
    ]
