# Generated by Django 5.0.1 on 2024-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_juree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('RF', 'Rap Francais'), ('G', 'Gospel'), ('D', 'Drill'), ('RnB', 'Rnb')], max_length=5),
        ),
    ]
